# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensor',
            name='year_in_school',
            field=models.CharField(choices=[('c', 'Car Manufacturer'), ('w', 'Wheels and Tires'), ('h', 'Hollywood'), ('m', 'Miscellaneous')], default='c', max_length=1),
        ),
    ]
