# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_licensor_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensor',
            old_name='year_in_school',
            new_name='lic_type',
        ),
    ]
