# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160205_2333'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='licensor',
            order_with_respect_to='name',
        ),
    ]
